# theme = "gruvbox_dark_hard"
theme = "gruvbox_dark_hard.custom"

[editor]
line-number = "relative"
mouse = false
scrolloff = 20
shell = ["zsh", "-c"]
bufferline = "always"
color-modes = true
completion-replace = true
cursorline = true
end-of-line-diagnostics = "hint"
inline-diagnostics.cursor-line = "warning"

[editor.auto-save]
focus-lost = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = true # false to show ignored files

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"F2" = "rename_symbol"
# open yazi file picker and choose file as buffer
"C-p" = [
  ':sh rm -f /tmp/helix_yazi_file_open',
  ':set mouse false',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/helix_yazi_file_open',
  ':redraw',
  ':set mouse true',
  ':open /tmp/helix_yazi_file_open',
  'select_all',
  'split_selection_on_newline',
  'goto_file',
  ':buffer-close! /tmp/helix_yazi_file_open',
]
# Move line up/down using A-k, A-j
"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
"A-j" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_down",
  "paste_before",
]
C-j = "scroll_down"
C-k = "scroll_up"
A-i = ":toggle lsp.display-inlay-hints"
# "S-f" = [":format"]
# override default delete and change to not yank 
A-d = "delete_selection"
d = "delete_selection_noyank"
A-c = "change_selection"
c = "change_selection_noyank"

[keys.insert]
"C-space" = "completion"
A-b = ["move_prev_word_start", "collapse_selection"]
A-w = ["move_next_word_end", "move_char_right"]

[keys.normal.space]
o = "file_picker_in_current_buffer_directory"

# Config Mode
[keys.normal."backspace"]
s = [":write"]
r = [":w", ":config-reload", ":reload-all"]
o = ":config-open"
g = [":new", ":insert-output lazygit", ":buffer-close", ":redraw", ":reload"]
t = [":sh wezterm cli spawn --cwd=%sh{pwd}  2>&1 >/dev/null"]
w = ":buffer-close"
# l = ":o ~/.config/helix/languages.toml"
