export * as puppeteer from "https://deno.land/x/puppeteer@16.2.0/mod.ts";
export * as cliffyColors from "jsr:@cliffy/ansi@1.0.0-rc.5/colors";
export * as cliffyCmd from "jsr:@cliffy/command@1.0.0-rc.5";
export * as cliffyTable from "jsr:@cliffy/table@1.0.0-rc.5";
export * as dax from "jsr:@david/dax@0.42.0";
export { intersect as stdIntersect } from "jsr:@std/collections@1.0.5/intersect";
export * as stdFS from "jsr:@std/fs@1.0.3";
export * as stdLog from "jsr:@std/log@0.224.7";
export type { FormatterFunction, Logger, LogRecord } from "jsr:@std/log@0.224.7";
export * as stdPath from "jsr:@std/path@1.0.4";
export * as stdSemver from "jsr:@std/semver@1.0.3";
export * as stdText from "jsr:@std/text@1.0.5";
export * as stdNodeFS from "node:fs";
export * as stdNodeUtil from "node:util";
export * as dateFns from "npm:date-fns@3.6.0";
export { default as handlebars } from "npm:handlebars@4.7.8";
